FROM eclipse/centos_jdk8

EXPOSE 22

LABEL maintainer="carusyte@163.com" \
      centos="" \
      tomcat="" \
      jdk="" \
      maven="" \
      git=""

ENV TZ=Asia/Hong_Kong

VOLUME [ "/home/user/.m2" ]

WORKDIR /projects

CMD ["tail", "-f", "/dev/null"]
